version: '3.7'
services:
  mongodb:
    container_name: mongodb_container
    image: mongo:${MONGO_VER:-5}
    environment: 
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_DATABASE=test
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
      - /opt/dbdata/sampledb/mongodb:/sampledb/mongodb
      - ~/.dockerc/mongodb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
volumes:
  data:

networks:
  default:
    external: true
    name: "${net:-entornet}"
